


export const USER_LOGIN_REQUEST="USER_LOGIN_REQUEST";

export const USER_LOGIN_SUCCESS="USER_LOGIN_SUCESS";

export const USER_LOGIN_FAIL="USER_LOGIN_FAIL";

export const USER_LOGOUT="USER_LOGOUT"




export const USER_REGISTER_REQUEST="USER_Register_REQUEST";

export const USER_REGISTER_SUCCESS="USER_Register_SUCESS";

export const USER_REGISTER_FAIL="USER_Register_FAIL";



export const USER_DETAILS_REQUEST=" USER_DETAILS_REQUEST"
export const USER_DETAILS_SUCESS=" USER_DETAILS_SUCESS"
export const USER_DETAILS_FAIL="USER_DETAILS_FAIL"
export const USER_DETAILS_Reset="USER_DETAILS_Reset"






export const USER_UPDATEPROFILE_REQUEST="USER_UPDATEPROFILE_REQUEST"
export const USER_UPDATEPROFILE_SUCESS="USER_UPDATEPROFILE_SUCESS"
export const USER_UPDATEPROFILE_FAIL="USER_UPDATEPROFILE_FAIL"
export const USER_UPDATEPROFILE_RESET="USER_UPDATEPROFILE_Reset"



export const USER_LIST_REQUEST=" USER_LIST_REQUEST"
export const USER_LIST_SUCESS="USER_LIST_SUCESS"
export const USER_LIST_FAIL=" const USER_LIST_FAIL"
export const USER_LIST_RESET=" USER_LIST_FAIL"





export const USER_DELETE_REQUEST="USER_DELETE_REQUEST"
export const USER_DELETE_SUCESS="USER_DELETE_SUCESS"
export const USER_DELETE_FAIL=" USER_DELETE_FAIL"





export const USER_UPDATE_REQUEST="USER_UPDATE_REQUEST"
export const USER_UPDATE_SUCESS="USER_UPDATE_SUCESS"
export const USER_UPDATE_FAIL="USER_UPDATE_FAIL"
export const USER_UPDATE_RESET="USER_UPDATE_FAIL"





export const singleUSER_DETAILS_REQUEST=" singleUSER_DETAILS_REQUEST"
export const singleUSER_DETAILS_SUCESS=" singleUSER_DETAILS_SUCESS"
export const singleUSER_DETAILS_FAIL="singleUSER_DETAILS_FAIL"
export const singleUSER_DETAILS_Reset="singleUSER_DETAILS_Reset"





